create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text unique not null,
  password_hash text,
  shipping_address text,
  created_at timestamptz default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text not null,
  price numeric(10, 2) not null,
  image_url text not null,
  stock integer not null default 0,
  is_default boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.cart_items (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete cascade,
  product_id bigint references public.products(id) on delete cascade,
  quantity integer not null default 1,
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id),
  customer_name text not null,
  customer_email text not null,
  shipping_address text not null,
  status text not null default 'Pending',
  payment_method text,
  total numeric(10, 2) not null,
  created_at timestamptz default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  product_name text not null,
  product_category text not null,
  product_image text not null,
  product_price numeric(10, 2) not null,
  quantity integer not null default 1
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_id bigint references public.products(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete cascade,
  customer_name text not null,
  customer_email text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text not null,
  created_at timestamptz default now(),
  unique (product_id, customer_id)
);